# Generated by Django 5.0.6 on 2024-05-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=10)),
                ('setor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProjeto', models.CharField(max_length=30)),
                ('numeroSei', models.CharField(max_length=21)),
                ('numeroParcela', models.CharField(max_length=20)),
                ('valorSolicitado', models.FloatField()),
                ('tituloProjeto', models.CharField(max_length=100)),
                ('statusTransacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginUsuario', models.CharField(max_length=100)),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cadastrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSolicitacao', models.DateTimeField()),
                ('dataConferenciaDocumentos', models.DateTimeField()),
                ('dataAutorizacaoEmpenho', models.DateTimeField()),
                ('dataConfeccaoEmpenho', models.DateTimeField()),
                ('numeroEmpenho', models.CharField(max_length=30)),
                ('dataConfeccaoTermo', models.DateTimeField()),
                ('dataEnvioTermo', models.DateTimeField()),
                ('numeroTermo', models.CharField(max_length=30)),
                ('responsavelConfeccao', models.CharField(max_length=100)),
                ('dataVistoTermo', models.DateTimeField()),
                ('dataEnvioTermProponente', models.DateTimeField()),
                ('dataAssinaturaTermo', models.DateTimeField()),
                ('dataEnvioPagamento', models.DateTimeField()),
                ('dataOrdemBancaria', models.DateTimeField()),
                ('statusTransacao', models.CharField(max_length=100)),
                ('projetoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTransacao', models.DateTimeField()),
                ('statusTransacao', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='transacaoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transacao'),
        ),
    ]
